# Generated by Django 4.1.1 on 2022-09-10 21:50

from django.db import migrations, models
import django.db.models.deletion
import teams.models
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('team_type', models.CharField(choices=[('EMAIL', 'E-Mail')], default='EMAIL', max_length=10)),
                ('send_time', models.TimeField()),
                ('next_send', models.DateTimeField()),
                ('timezone', timezone_field.fields.TimeZoneField(choices_display='STANDARD', default='America/Chicago', use_pytz=False)),
                ('days', models.JSONField(default=teams.models.days_default)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
