# Generated by Django 4.1.2 on 2022-10-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_scrum_emailmember_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='hours_open',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
    ]
