# Generated by Django 4.1.2 on 2022-10-23 11:10

from django.db import migrations, models
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_hours_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='questions',
            field=models.JSONField(default=teams.models.DEFAULT_QUESTIONS),
        ),
    ]
