# Generated by Django 4.1.2 on 2022-10-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
