# Generated by Django 4.1.4 on 2022-12-22 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_status_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='next_report',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 15, 46, 23, 535529, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='report_sent',
            field=models.BooleanField(default=False),
        ),
    ]
