# Generated by Django 4.1.4 on 2022-12-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_next_report_team_report_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='next_report',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
