# Generated by Django 4.1.4 on 2022-12-26 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0007_alter_team_next_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='report_sent',
        ),
        migrations.AddField(
            model_name='team',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
