# Generated by Django 4.1.4 on 2022-12-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_remove_team_report_sent_team_owners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrum',
            options={'get_latest_by': '-created', 'ordering': ['-created']},
        ),
    ]
