# Generated by Django 4.1.4 on 2022-12-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_scrum_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrum',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
    ]
