# Generated by Django 4.1.4 on 2022-12-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_alter_scrum_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailMember',
            new_name='Member',
        ),
    ]
