# Generated by Django 4.1.4 on 2022-12-29 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_organization_created_organization_modified'),
        ('teams', '0012_remove_member_email_remove_member_name_member_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='owners',
        ),
        migrations.AddField(
            model_name='team',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.organization'),
        ),
    ]
