# Generated by Django 4.1.5 on 2023-01-02 16:59

import django.contrib.postgres.fields
from django.db import migrations, models
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_member_report_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='days',
        ),
        migrations.AddField(
            model_name='team',
            name='days_of_week',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=25), default=teams.models.default_days, size=None),
        ),
    ]
