# Generated by Django 4.1.5 on 2023-03-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'scrum member'},
        ),
    ]
