# Generated by Django 4.1.4 on 2022-12-29 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_organization_orgmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 29, 16, 2, 52, 408524, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
