# Generated by Django 4.1.5 on 2023-01-04 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_organization_created_organization_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateTimeField()),
                ('level', models.CharField(choices=[('trial', 'Trial'), ('level-0', 'Level 0'), ('level-1', 'Level 1'), ('level-2', 'Level 2'), ('level-3', 'Level 3')], default='trial', max_length=10)),
                ('cancelled', models.BooleanField(default=False)),
                ('subscription', models.CharField(blank=True, max_length=155, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
            ],
            options={
                'ordering': ['-expiration'],
            },
        ),
    ]
