# Generated by Django 4.1.5 on 2023-01-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
