# Generated by Django 4.1.5 on 2023-01-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_credit_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['-expiration', '-created']},
        ),
    ]
