# Generated by Django 4.1.5 on 2023-01-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_credit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='upgraded_level',
            field=models.CharField(blank=True, choices=[('trial', 'Trial'), ('level-0', 'Level 0'), ('level-1', 'Level 1'), ('level-2', 'Level 2'), ('level-3', 'Level 3')], max_length=10, null=True),
        ),
    ]
