# Generated by Django 4.1.7 on 2023-03-06 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_credit_upgraded_level'),
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.organization'),
            preserve_default=False,
        ),
    ]
