# Generated by Django 4.1.7 on 2023-03-06 22:59

from django.db import migrations, models
import wiki.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_wiki_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.CharField(max_length=150, validators=[wiki.models.validate_path]),
        ),
    ]
