# Generated by Django 4.1.7 on 2023-03-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_version_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-publish_on']},
        ),
    ]
