# Generated by Django 4.1.7 on 2023-03-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_alter_version_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='show_in_nav',
            field=models.BooleanField(default=False, verbose_name='Show in Navigation'),
        ),
    ]
